spring:
  application:
    name: digital-clock
  datasource:
    url: jdbc:mysql://localhost:3306/digital_clock_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

server:
  port: 8080